apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-server
  name: conductor-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yaml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: conductor-server
    spec:
      containers:
      - env:
        - name: CONFIG_PROP
          value: config-redis.properties
        image: amimimor/conductor:server 
        imagePullPolicy: ""
        name: conductor-server
        volumeMounts:
        - name: "config-redis"
          mountPath: "/app/config/config-redis.properties"
          subPath: "config-redis.properties"
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: 
        - name: "config-redis"
          configMap:
            name: "config-redis"
    
status: {}
