apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conductor-ui
  name: conductor-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: conductor-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yaml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: conductor-ui
    spec:
      containers:
      - env:
        - name: WF_SERVER
          value: http://conductor-server:8080/api/
        image: amimimor/conductor:ui
        imagePullPolicy: ""
        name: conductor-ui
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
