apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dynomite
  name: dynomite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dynomite
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-kompose.yaml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/internal: "true"
        io.kompose.service: dynomite
    spec:
      containers:
      - image: v1r3n/dynomite
        imagePullPolicy: ""
        name: dynomite
        ports:
        - containerPort: 8102
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
