apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dynomite
  name: dynomite
spec:
  ports:
  - name: "8102"
    port: 8102
    targetPort: 8102
  selector:
    io.kompose.service: dynomite
status:
  loadBalancer: {}
